"""expand vehicle profile add maintenance and health snapshot models

Revision ID: 0570127a6a1e
Revises: 2e7d3a01f6a3
Create Date: 2026-04-12 23:22:40.026510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0570127a6a1e'
down_revision = '2e7d3a01f6a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('fuel_level', sa.Float(), nullable=True),
    sa.Column('engine_temp', sa.Float(), nullable=True),
    sa.Column('check_engine_light', sa.Boolean(), nullable=False),
    sa.Column('battery_status', sa.String(length=50), nullable=True),
    sa.Column('tire_status', sa.String(length=50), nullable=True),
    sa.Column('brake_status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fuel_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('transmission', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('purchase_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('purchase_date')
        batch_op.drop_column('transmission')
        batch_op.drop_column('fuel_type')
        batch_op.drop_column('nickname')

    op.drop_table('maintenance_records')
    op.drop_table('health_snapshots')
    # ### end Alembic commands ###
