"""add vehicle_logs table

Revision ID: 2e7d3a01f6a3
Revises: 10944bf0b574
Create Date: 2026-02-01 09:09:22.467577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e7d3a01f6a3'
down_revision = '10944bf0b574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('fuel_level', sa.Integer(), nullable=True),
    sa.Column('engine_temp', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_logs_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_logs_created_at'))

    op.drop_table('vehicle_logs')
    # ### end Alembic commands ###
